Solved KeyError: 'confidence' for redacted files.
Changes to solve following error on redacted json files:

Traceback (most recent call last):
  File "transcript.py", line 82, in convert_transcription
    transcription = process_speaker_labels(data)
  File "transcript.py", line 253, in process_speaker_labels
    confidence = item['alternatives'][0]['confidence']
KeyError: 'confidence'